### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh-alexa-skill#1]
* [x] Build native image
* [ ] Deploy to zeit.co
* [x] Add docker file for non-native image setup (fallback)
* [ ] Add blogpost
* [x] Add i18n support (skill is currently german only)
* [ ] Refactor speechText handling - Use non-blocking option
* [x] Add number conversion for very high values (e.g. price of STS)
* [ ] Add skill intent / slot definitions to github repo
* [x] Add configuration handling
* [x] Use API key instead of `admin/admin` login
* [ ] Use different text for wall views
